AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - db/schema.rb

Style/Documentation:
  Enabled: false

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
