AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - db/schema.rb

RSpec/ExampleLength:
  Max: 12

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
